using GT = Gadgeteer;
using GTM = Gadgeteer.Modules;
using GTI = Gadgeteer.Interfaces;

namespace Gadgeteer.Modules.GHIElectronics
{
    // -- CHANGE FOR MICRO FRAMEWORK 4.2 --
    // If you want to use Serial, SPI, or DaisyLink (which includes GTI.SoftwareI2C), you must do a few more steps
    // since these have been moved to separate assemblies for NETMF 4.2 (to reduce the minimum memory footprint of Gadgeteer)
    // 1) add a reference to the assembly (named Gadgeteer.[interfacename])
    // 2) in GadgeteerHardware.xml, uncomment the lines under <Assemblies> so that end user apps using this module also add a reference.

    /// <summary>
    /// A passive infrared module that is used to detect motion in the module's field of view for Microsoft .NET Gadgeteer.
    /// </summary>
    /// <example>
    /// <para>The following example uses a <see cref="PIR"/> object to detect motion and raise an event. 
    /// </para>
    /// <code>
    /// using System;
    /// using System.Collections;
    /// using System.Threading;
    /// using Microsoft.SPOT;
    /// using Microsoft.SPOT.Presentation;
    /// using Microsoft.SPOT.Presentation.Controls;
    /// using Microsoft.SPOT.Presentation.Media;
    /// using Microsoft.SPOT.Touch;
    ///
    /// using Gadgeteer.Networking;
    /// using GT = Gadgeteer;
    /// using GTM = Gadgeteer.Modules;
    /// using Gadgeteer.Modules.GHIElectronics;
    ///
    /// namespace TestApp
    /// {
    ///     public partial class Program
    ///     {
    ///         void ProgramStarted()
    ///         {
    ///             motion_Sensor.Motion_Sensed += new PIR.MotionSensorEventHandler(motion_Sensor_Motion_Sensed);
    ///         }
    ///
    ///         void motion_Sensor_Motion_Sensed(PIR sender, PIR.MotionSensorState state)
    ///         {
    ///             Debug.Print("Motion Detected!");
    ///         }
    ///     }
    /// }
    /// </code>
    /// </example>
    public class PIR : GTM.Module
    {
        private GTI.InterruptInput m_motionDetect;
        // Note: A constructor summary is auto-generated by the doc builder.
        /// <summary></summary>
        /// <param name="socketNumber">The socket that this module is plugged in to.</param>
        public PIR(int socketNumber)
        {
            // This finds the Socket instance from the user-specified socket number.  
            // This will generate user-friendly error messages if the socket is invalid.
            // If there is more than one socket on this module, then instead of "null" for the last parameter, 
            // put text that identifies the socket to the user (e.g. "S" if there is a socket type S)
            Socket socket = Socket.GetSocket(socketNumber, true, this, null);

            // This creates an GTI.InterruptInput interface. The interfaces under the GTI namespace provide easy ways to build common modules.
            // This also generates user-friendly error messages automatically, e.g. if the user chooses a socket incompatible with an interrupt input.
            this.m_motionDetect = new GTI.InterruptInput(socket, GT.Socket.Pin.Three, GTI.GlitchFilterMode.On, GTI.ResistorMode.PullUp, GTI.InterruptMode.RisingAndFallingEdge, this);

            // This registers a handler for the interrupt event of the interrupt input (which is below)
            this.m_motionDetect.Interrupt += new GTI.InterruptInput.InterruptEventHandler(this._input_Interrupt);
        }

        private void _input_Interrupt(GTI.InterruptInput input, bool value)
        {
            this.OnMotionSensorEvent(this, value ? MotionSensorState.Ready : MotionSensorState.Busy);
        }

        /// <summary>
        /// Gets a value that indicates whether the sensor is still high after detecthing motion.
        /// </summary>
        public bool SensorStillActive
        {
            get
            {
                return this.m_motionDetect.Read();
            }
        }

        /// <summary>
        /// Represents the state of the <see cref="PIR"/> object.
        /// </summary>
        public enum MotionSensorState
        {
            /// <summary>
            /// The state of the sensor is low, which means it is now ready to begin detecting motion again.
            /// </summary>
            Ready = 0,
            /// <summary>
            /// The state of the sensor is high, which means it is not ready to begin detecting motion again.
            /// </summary>
            Busy = 1
        }

        /// <summary>
        /// Represents the delegate that is used to handle the <see cref="Motion_Sensed"/> event.
        /// </summary>
        /// <param name="sender">The <see cref="PIR"/> object that raised the event.</param>
        /// <param name="state">The state of the PIR</param>
        public delegate void MotionSensorEventHandler(PIR sender, MotionSensorState state);

        /// <summary>
        /// Raised when the state of <see cref="PIR"/> is high.
        /// </summary>
        /// <remarks>
        /// Implement this event handler when you want to provide an action associated with PIR activity.
        /// The state of the PIR is passed to the <see cref="MotionSensorEventHandler"/> delegate,
        /// so you can use the same event handler for both PIR states.
        /// </remarks>
        public event MotionSensorEventHandler Motion_Sensed;

        private MotionSensorEventHandler onMotionSensor;

        /// <summary>
        /// Raises the <see cref="Motion_Sensed"/> event.
        /// </summary>
        /// <param name="sender">The <see cref="PIR"/> that raised the event.</param>
        /// <param name="MotionSensorState">The state of the PIR.</param>
        protected virtual void OnMotionSensorEvent(PIR sender, MotionSensorState MotionSensorState)
        {
            if (this.onMotionSensor == null)
            {
                this.onMotionSensor = new MotionSensorEventHandler(this.OnMotionSensorEvent);
            }

            if (Program.CheckAndInvoke(this.Motion_Sensed, this.onMotionSensor, sender, MotionSensorState))
            {
                switch (MotionSensorState)
                {
                    case MotionSensorState.Busy:
                        this.Motion_Sensed(sender, MotionSensorState);
                        break;
                }
            }
        }
    }
}