//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LED7C_Tester {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Display T43 module using sockets 15, 16, 17 and 14 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.DisplayT43 displayT43;
        
        /// <summary>The LED 7C module using socket 18 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C1;
        
        /// <summary>The LED 7C module using socket 13 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C2;
        
        /// <summary>The LED 7C module using socket 12 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C3;
        
        /// <summary>The LED 7C module using socket 11 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C4;
        
        /// <summary>The LED 7C module using socket 10 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C5;
        
        /// <summary>The LED 7C module using socket 9 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C6;
        
        /// <summary>The LED 7C module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C7;
        
        /// <summary>The LED 7C module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C8;
        
        /// <summary>The LED 7C module using socket 2 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C9;
        
        /// <summary>The LED 7C module using socket 1 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED7C led7C10;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZRaptor Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZRaptor)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZRaptor();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.displayT43 = new GTM.GHIElectronics.DisplayT43(15, 16, 17, 14);
            this.led7C1 = new GTM.GHIElectronics.LED7C(18);
            this.led7C2 = new GTM.GHIElectronics.LED7C(13);
            this.led7C3 = new GTM.GHIElectronics.LED7C(12);
            this.led7C4 = new GTM.GHIElectronics.LED7C(11);
            this.led7C5 = new GTM.GHIElectronics.LED7C(10);
            this.led7C6 = new GTM.GHIElectronics.LED7C(9);
            this.led7C7 = new GTM.GHIElectronics.LED7C(4);
            this.led7C8 = new GTM.GHIElectronics.LED7C(3);
            this.led7C9 = new GTM.GHIElectronics.LED7C(2);
            this.led7C10 = new GTM.GHIElectronics.LED7C(1);
        }
    }
}
