//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Display_T35 module using sockets 14, 13 and 12 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Display_T35 display_T35;
        
        /// <summary>The TouchC8 module using socket 3 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.TouchC8 touchC8;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZSpider_II Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZSpider_II)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider_II();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.display_T35 = new GTM.GHIElectronics.Display_T35(14, 13, 12, Socket.Unused);
            this.touchC8 = new GTM.GHIElectronics.TouchC8(3);
        }
    }
}
