using GTM = Gadgeteer.Modules;
using GTI = Gadgeteer.Interfaces;

namespace Gadgeteer.Modules.GHIElectronics
{
    /// <summary>
    /// Represents a potentiometer module.
    /// </summary>
    public class Potentiometer : GTM.Module
    {
        // Note: A constructor summary is auto-generated by the doc builder.
        /// <summary></summary>
        /// <param name="socketNumber">The mainboard socket that has the module plugged into it.</param>
        public Potentiometer(int socketNumber)
        {
            Socket socket = Socket.GetSocket(socketNumber, true, this, null);
            this.input = new GTI.AnalogInput(socket, Socket.Pin.Three, this);
        }


        private GTI.AnalogInput input;

        /// <summary>
        /// Returns the current voltage reading of the potentiometer
        /// </summary>
        public double ReadPotentiometerVoltage()
        {
            return input.ReadVoltage();
        }

        /// <summary>
        ///  Returns the current position of the potentiometer relative to its maximum: range 0.0 to 1.0
        /// </summary>
        public double ReadPotentiometerPercentage()
        {
            return input.ReadProportion();
        }

    }
}
