//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp {
    using Gadgeteer;
    using GTM = Gadgeteer.Modules;
    
    
    public partial class Program : Gadgeteer.Program {
        
        /// <summary>The Button module using socket 10 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.Button button;
        
        /// <summary>The RS485 module using socket 4 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.RS485 rs485;
        
        /// <summary>The RS485 module using socket 8 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.RS485 rs4852;
        
        /// <summary>The LED Strip module using socket 5 of the mainboard.</summary>
        private Gadgeteer.Modules.GHIElectronics.LED_Strip led_Strip;
        
        /// <summary>This property provides access to the Mainboard API. This is normally not necessary for an end user program.</summary>
        protected new static GHIElectronics.Gadgeteer.FEZSpider Mainboard {
            get {
                return ((GHIElectronics.Gadgeteer.FEZSpider)(Gadgeteer.Program.Mainboard));
            }
            set {
                Gadgeteer.Program.Mainboard = value;
            }
        }
        
        /// <summary>This method runs automatically when the device is powered, and calls ProgramStarted.</summary>
        public static void Main() {
            // Important to initialize the Mainboard first
            Program.Mainboard = new GHIElectronics.Gadgeteer.FEZSpider();
            Program p = new Program();
            p.InitializeModules();
            p.ProgramStarted();
            // Starts Dispatcher
            p.Run();
        }
        
        private void InitializeModules() {
            this.button = new GTM.GHIElectronics.Button(10);
            this.rs485 = new GTM.GHIElectronics.RS485(4);
            this.rs4852 = new GTM.GHIElectronics.RS485(8);
            this.led_Strip = new GTM.GHIElectronics.LED_Strip(5);
        }
    }
}
